Repository CS2113-AY1819S1-F10-1/main, pull requests merged in 2018-11, with the labels that each got.

#153 Exam update to match org
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Exam.png
  docs/images/RegisterExam_Sequence_Diagram.png
  docs/team/MeghanaProjectPortfolio.adoc
  docs/team/micklwl.adoc
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/assessment/AddAssignmentStatistics.java
  src/seedu/addressbook/commands/attendance/ReplaceAttendanceCommand.java
  src/seedu/addressbook/commands/attendance/UpdateAttendanceCommand.java
  src/seedu/addressbook/commands/attendance/ViewAttendanceDateCommand.java
  src/seedu/addressbook/commands/attendance/ViewAttendancePersonCommand.java
  src/seedu/addressbook/commands/commandresult/CommandResult.java
  src/seedu/addressbook/commands/exams/DeleteExamCommand.java
  src/seedu/addressbook/commands/exams/DeregisterExamCommand.java
  src/seedu/addressbook/commands/exams/EditExamCommand.java
  src/seedu/addressbook/commands/exams/RegisterExamCommand.java
  src/seedu/addressbook/commands/exams/ViewExamsCommand.java
  src/seedu/addressbook/commands/person/DeleteCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/ExamBook.java
  src/seedu/addressbook/data/person/Exam.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/UniqueExamList.java
  src/seedu/addressbook/data/person/UniquePersonList.java
  src/seedu/addressbook/formatter/Formatter.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/privilege/user/BasicUser.java
  src/seedu/addressbook/privilege/user/TutorUser.java
  src/seedu/addressbook/storage/Storage.java
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/storage/jaxb/AdaptedPerson.java
  test/java/seedu/addressbook/TestDataHelper.java
  test/java/seedu/addressbook/logic/AttendanceTest.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
  test/java/seedu/addressbook/storage/StorageFileTest.java
  test/java/seedu/addressbook/stubs/StorageStub.java
Labels: Ready To Merge

#170 Bug fixes + Update to UG
  docs/UserGuide.adoc
  docs/team/MeghanaProjectPortfolio.adoc
  src/seedu/addressbook/commands/assessment/AddGradesCommand.java
  src/seedu/addressbook/commands/general/HelpCommand.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/privilege/user/TutorUser.java
  src/seedu/addressbook/storage/jaxb/AdaptedAssessment.java
  src/seedu/addressbook/storage/jaxb/AdaptedPerson.java
  src/seedu/addressbook/ui/MainWindow.java
Labels: Ready To Merge

#172 Update command categories
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/assessment/AddAssessmentCommand.java
  src/seedu/addressbook/commands/assessment/AddAssignmentStatistics.java
  src/seedu/addressbook/commands/assessment/ViewGradesCommand.java
  src/seedu/addressbook/commands/attendance/ReplaceAttendanceCommand.java
  src/seedu/addressbook/commands/attendance/UpdateAttendanceCommand.java
  src/seedu/addressbook/commands/attendance/ViewAttendanceDateCommand.java
  src/seedu/addressbook/commands/attendance/ViewAttendancePersonCommand.java
  src/seedu/addressbook/commands/fees/EditFeesCommand.java
  src/seedu/addressbook/commands/fees/ListDueFeesCommand.java
  src/seedu/addressbook/commands/fees/ListFeesCommand.java
  src/seedu/addressbook/commands/fees/ViewFeesCommand.java
Labels: Ready To Merge

#174 V1.3 fees fix
  src/seedu/addressbook/commands/fees/ListFeesCommand.java
  src/seedu/addressbook/data/person/UniquePersonList.java
Labels: Ready To Merge, priority.high, severity.High

#184 Update ug command symbols
  docs/UserGuide.adoc
Labels: Ready To Merge

#185 Update Docs
  README.adoc
  docs/AboutUs.adoc
  docs/team/meg1456.adoc
  docs/team/micklwl.adoc
Labels: Ready To Merge

#205 V1.4 Exam
  docs/UsingGradle.adoc
  src/seedu/addressbook/commands/commandformat/indexformat/IndexFormatCommand.java
  src/seedu/addressbook/commands/exams/AddExamCommand.java
  src/seedu/addressbook/commands/exams/ClearExamsCommand.java
  src/seedu/addressbook/commands/exams/DeleteExamCommand.java
  src/seedu/addressbook/commands/exams/DeregisterExamCommand.java
  src/seedu/addressbook/commands/exams/EditExamCommand.java
  src/seedu/addressbook/commands/exams/ExamsListCommand.java
  src/seedu/addressbook/commands/exams/RegisterExamCommand.java
  src/seedu/addressbook/commands/person/ClearCommand.java
  src/seedu/addressbook/data/ExamBook.java
  src/seedu/addressbook/data/person/Exam.java
  src/seedu/addressbook/data/person/ReadOnlyExam.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/UniqueExamList.java
  src/seedu/addressbook/formatter/Formatter.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/storage/jaxb/AdaptedAddressBook.java
  test/java/seedu/addressbook/FormatterTest.java
  test/java/seedu/addressbook/TestDataHelper.java
  test/java/seedu/addressbook/logic/AccountTest.java
  test/java/seedu/addressbook/logic/AssessmentCommandsTest.java
  test/java/seedu/addressbook/logic/AttendanceTest.java
  test/java/seedu/addressbook/logic/ExamCommandsTest.java
  test/java/seedu/addressbook/logic/FeesCommandsTest.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/PrivilegeTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
  test/java/seedu/addressbook/storage/StorageFileTest.java
Labels: Ready To Merge

#221 V1.4 Fees
  log.txt.1
  src/seedu/addressbook/commands/fees/EditFeesCommand.java
  src/seedu/addressbook/commands/fees/ListDueFeesCommand.java
  src/seedu/addressbook/commands/fees/PaidFeesCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/person/Fees.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/UniquePersonList.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/privilege/user/AdminUser.java
  test/java/seedu/addressbook/FormatterTest.java
  test/java/seedu/addressbook/TestDataHelper.java
  test/java/seedu/addressbook/logic/FeesCommandsTest.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: Ready To Merge, priority.high

#227 Update messages for exams commands
  src/seedu/addressbook/commands/exams/DeregisterExamCommand.java
  src/seedu/addressbook/commands/exams/RegisterExamCommand.java
  src/seedu/addressbook/commands/exams/ViewExamsCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/person/Exam.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/storage/StorageFile.java
  test/java/seedu/addressbook/common/UtilsTest.java
  test/java/seedu/addressbook/logic/ExamCommandsTest.java
  test/java/seedu/addressbook/storage/StorageFileTest.java
Labels: Ready To Merge

#228 Rename tests in StorageFileTest
  test/java/seedu/addressbook/storage/StorageFileTest.java
Labels: Ready To Merge

#206 UG + DG update
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/LearningOutcomes.adoc
  docs/UserGuide.adoc
  docs/team/micklwl.adoc
Labels: Ready To Merge

#225 V1.4 Fees documentation
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/EditFeesSequenceDiag.png
  docs/images/FeesClassDiag.png
  docs/team/lucdx.adoc
Labels: Ready To Merge

#230 V1.41 Fees Bug Fixes
  src/seedu/addressbook/commands/fees/EditFeesCommand.java
  src/seedu/addressbook/commands/fees/PaidFeesCommand.java
  src/seedu/addressbook/commands/fees/ViewFeesCommand.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/person/Fees.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/FormatterTest.java
  test/java/seedu/addressbook/logic/FeesCommandsTest.java
Labels: Ready To Merge

#271 Updated from the review
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/exams/EditExamCommand.java
  src/seedu/addressbook/commands/exams/ListExamsCommand.java
  src/seedu/addressbook/data/person/ReadOnlyExam.java
  src/seedu/addressbook/formatter/Formatter.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/privilege/user/TutorUser.java
  src/seedu/addressbook/ui/Gui.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/CommandResultTest.java
  test/java/seedu/addressbook/FormatterTest.java
  test/java/seedu/addressbook/TestDataHelper.java
  test/java/seedu/addressbook/logic/AccountTest.java
  test/java/seedu/addressbook/logic/AssessmentCommandsTest.java
  test/java/seedu/addressbook/logic/AttendanceTest.java
  test/java/seedu/addressbook/logic/CommandAssertions.java
  test/java/seedu/addressbook/logic/ExamCommandsTest.java
  test/java/seedu/addressbook/logic/FeesCommandsTest.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/PrivilegeTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
  test/java/seedu/addressbook/stubs/StorageStub.java
Labels: Ready To Merge

#274 Ppp
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Exam.png
  docs/team/micklwl.adoc
  sample_data/exams.txt
  src/seedu/addressbook/privilege/user/AdminUser.java
  src/seedu/addressbook/privilege/user/TutorUser.java
Labels: Ready To Merge

#287 V1.41 general doc
  README.adoc
  docs/DeveloperGuide.adoc
Labels: Ready To Merge

#294 Correct errors + format
  _reposense/config.json
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/stylesheets/asciidoctor.css
Labels: Ready To Merge, lastMinuteChecks
